### ISSUE TITLE
Value does not reset after an amount greater than MAX_PARTICLES is typed in the text field

### ISSUE THREAD

**Issue by alexmat2on** [ccnydss/bioanimation#61]
Look at the `updateParticles` function inside of `Simulator.js`, which is where the alert pop-up appears when an amount over the maximum is entered. After the pop-up, we should change the inputs to reflect the max amount of particles instead of the user input. 

Use the `updateInputLoc` function instead of the `evt...` stuff.

**Comment by chen0gao** [comment]
Commit: https://github.com/ccnydss/bioanimation/commit/00206f7036da5dda7f2409e42b284a5dfb45ca49

updateInputLoc is triggered, but will not update the value,
so I just add the constraint in InputRow.js
```
  value(setter) {
    if (typeof setter === 'undefined') {
      this.values = Number(this.values);
      return this.values;
    }
    else {
```
> if(setter>animationSequencer.current().MAX_PARTICLES)
> setter=animationSequencer.current().MAX_PARTICLES
> if(setter<animationSequencer.current().MIN_PARTICLES)
> setter=animationSequencer.current().MIN_PARTICLES

```
      this.values = setter;
      this.dom.input.value(setter);
    }
```

**Comment by chen0gao** [comment]
https://github.com/ccnydss/bioanimation/blob/f2271fc4a206778e70e8fbb770ac3f95db06b3a6/js/obj/sim/InputRow.js#L121-L124
